Part1
SmartPhoneJava/technopark pull request #1
Opened 2018-10-03 10:26 UTC by SmartPhoneJava

Первое задание первой лабораторной, runId 671

2018-10-03 11:32 UTC, leshiy1295 requested changes
Исправьте замечания и пришлите повторно на ревью после успешного прохождения в АСТС с указанием нового runId.
На первый раз постарался максимально комментировать код - впоследствии - скорее всего - буду комментировать только для первой встреченной ошибки - тогда все аналогичные ситуации нужно будет найти и переработать самостоятельно

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +int lowRegistr(char **arr, int arr_size, char ***save)
лучше явно показать, что arr - это указатель на массив, а не просто двойной указатель
*** лучше разбить на typedef -  указателя на массив и использовать тут указатель на этот тип

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +#define POSITION_OF_FIRST_CAPITAL_EN 65
в этом нет необходимости, так как char - это целый тип, то есть, например, 'a' в контексте целого числа вернёт код этого символа

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	for (char *ch = arr; *ch != 0; ch++, size++);
стоит при работе со строками оперировать с '\0'

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	int size = 0;
для size имеет смысл использовать тип size_t

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +int len(char* arr)
лучше явно указать, что тут ожидается массив

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	assert(save != NULL);
а почему save должен выделяться снаружи?
итоговое число обработанных строк формируется же внутри

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +do
тут что-то пошло не так с отступами

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +int main(int argc, char* argv[])
лучше структурировать программный файл следующим образом:
- описания функций
- определение функции main
- определение остальных функций

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	setbuf(stdout,NULL);
зачем это нужно?

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +   char **arr = (char**)calloc(BUFFER_SIZE, sizeof(char*));
что, если произошла ошибка?

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	arr[i] = (char*)calloc(BUFFER_SIZE, sizeof(char));
аналогично - нет обработки ошибок

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +while (my_getdelim(&arr[i++], &max_size, '\n', stdin) != -1);
-1 - магическая константа. У Вас же есть специальный макрос для этого?

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +				printf("\n");
лучше всегда без исключения ставить фигурные скобки для предотвращения глупых ошибок

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +				printf("\n");
а почему не поместили просто \n внутрь printf?
мне кажется, что система допускает в конце символ \n

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +			free(arr[f]);
лучше разнести смысловую нагрузку от освобождения памяти

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +   else
функция main получилась слишком сложная. В идеале она должна выглядеть следующим образом:
- инициализация
- вызов функции для ввода значений
- вызов основной функции-обработчика
- вызов функции для вывода результатов
- освобождение ресурсов

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +                return -1;
делать return внутри цикла - нехорошо
+ тут используется магическая константа

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +		if (c == delimiter)
отступы и скобки

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +            return -1;
что произойдёт с *lineptr?

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +    while ((c = fgetc(stream)) != EOF)// && c != delimiter)
комментариев с нерабочим кодом быть не должно

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +int my_getdelim(char **lineptr, int *n, int delimiter, FILE *stream)
название функции непонятное и не говорит о её сути
также рекомендуется помечать неизменяемые поля как const, если такие присутствуют

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +int my_getdelim(char **lineptr, int *n, int delimiter, FILE *stream)
безопаснее работать с локальными изменениями вплоть до завершения работы функции.
Иначе может возникнуть не консистентное состояние - например, n Вы изменили, а память выделить не удалось
И вообще - не очень хорошо менять выходные параметры по ходу функции

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +    while ((c = fgetc(stream)) != EOF)// && c != delimiter)
на данном этапе c - это int
нужно получить char для дальнейшей работы

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +    if (count == 0)
скобки + магические константы

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	for (int i = 0; i < arr_size; i++)
лучше использовать size_t

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +			for (; i >= 0; i--){
в случае использования size_t тут могут возникнуть проблемы, так как цикл будет выполняться вечно

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +				arr[i][j] = arr[i][j] + OFFSET;
задавать с помощью #define OFFSET тоже необязательно, поскольку его можно вычислить через разность соответствующих символов

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +		//(*save)[i][row_size] = 0;
что за комментарий?

2018-10-03 11:32 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	// размер строки
писать комментарий к каждой строке - плохая практика, код должен быть самодокументируемый, то есть являться документацией сам по себе и не нуждаться в доп. пояснениях. Использовать комментарии следует только в случае, если решение не очевидно - тут же он просто дублирует очевидную семантику кода, поэтому стоит убрать

2018-10-03 11:54 UTC, leshiy1295 commented on deep_c/1/part1.c
> +#include <assert.h>
assert работает в DEBUG-режиме.
В RELEASE он игнорируется, поэтому при наличии ошибочного ввода программа это никак не обработает => нужно в любом случае после assert добавить проверку корректности ввода и правильно завершать работу функции

2018-10-03 11:57 UTC, SmartPhoneJava commented on deep_c/1/part1.c
> +	assert(save != NULL);
Так ведь мы передаем адрес указателя на массив, который ниже разыменовывается. Если передадут NULL, то не получится разыменовать и выделить память

2018-10-03 12:04 UTC, SmartPhoneJava commented on deep_c/1/part1.c
> +	setbuf(stdout,NULL);
Без этого не работает считывание из командой строки(хотя похоже, что это только на виндоус так...)

2018-10-03 12:10 UTC, SmartPhoneJava commented on deep_c/1/part1.c
> +				printf("\n");
А если в теле условия идет return? Например if (!tmp) return ERROR;

2018-10-03 12:16 UTC, leshiy1295 commented on deep_c/1/part1.c
> +				printf("\n");
лучше писать всегда - return можно пропустить глазами, особенно если условие замудрённое, а также после того, как ревьюер просмотрел код тела и вспоминает, какое условие вообще было

2018-10-03 12:17 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	assert(save != NULL);
да, тут Вы правы.
но как раз для того, чтобы подобные вопросы не возникали, лучше не передавать конструкцию сложнее двойного указателя.

2018-10-03 12:50 UTC, SmartPhoneJava commented on deep_c/1/part1.c
> +		//(*save)[i][row_size] = 0;
В первых реализациях выделял память с помощью malloc, поэтому надо было явно указывать символ конца строки, но с calloc необходимость в этом отпала. Удалил эту строчку

2018-10-03 14:12 UTC, SmartPhoneJava reviewed
runID 773

2018-10-03 21:12 UTC, leshiy1295 requested changes
нужно прогнать свою программу через статические анализаторы cppcheck, clang_formatter или ещё какие-нибудь, о которых рассказывалось на семинаре, и поправить все замечания по форматированию кода

2018-10-03 21:12 UTC, leshiy1295 commented on alg/1/1/lab1/main.cpp
> +#include <QCoreApplication>
что это за файлы?

2018-10-03 21:12 UTC, leshiy1295 commented on deep_c/1/part1.c
> +void printText(char* text[], const size_t kolvo);
почему, например, тут text не const?

2018-10-03 21:12 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	string_ptr arr = (char**)calloc(BUFFER_SIZE, sizeof(char*));
что, если calloc вернул ошибку?

2018-10-03 21:12 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	wchar_t letter_a = L'а';
зачем используется wchar_t?
русские символы вполне умещаются в один байт в кодировке ANSI

2018-10-03 21:12 UTC, leshiy1295 commented on deep_c/1/part1.c
> +			} else if((arr[i][j]  >= 'A')
либо уж использовать константы, либо нет
особого смысла тут использовать константы нет
вдобавок ко всему - стоит вынести в отдельный метод

2018-10-03 21:12 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	if (i == 0)
с отступами и скобками всё равно не всё поправлено

2018-10-03 21:18 UTC, SmartPhoneJava commented on deep_c/1/part1.c
> +	wchar_t letter_a = L'а';
Если использовать просто char, то есть писать напрямую как с латиницей, то компилятор выдает следующее предупреждение

part1.c:127:18: warning: multi-character character constant [-Wmultichar]
    (arr[i][j] <= 'а'))
                  ^~~~
В гугле нашел, что эту проблему решает с помощью wchar_t для кириллицы

2018-10-03 21:21 UTC, SmartPhoneJava commented on alg/1/1/lab1/main.cpp
> +#include <QCoreApplication>
Это я начинал делать ДЗ по алгоритмам в QT и при инициализации проекта создалось. Сейчас уберу из версионного контроля

2018-10-03 21:30 UTC, SmartPhoneJava commented on deep_c/1/part1.c
> +void printText(char* text[], const size_t kolvo);
Если поставить сюда const, то и посылать в эту функцию надо const char **, но переменная text типа char* [] - указатель на строки, каждая из которых в свою очередь инициализируется в функции lowRegistr и поэтому const не поставить

2018-10-04 09:39 UTC, leshiy1295 requested changes

2018-10-04 09:39 UTC, leshiy1295 commented on deep_c/1/part1.c
> +void printText(string_ptr text, const size_t kolvo);
kolvo - не стоит писать транслитом

2018-10-04 09:39 UTC, leshiy1295 commented on deep_c/1/part1.c
> +size_t lowRegistr(char* arr[], const size_t arr_size, string_ptr* save) {
в C предпочтителен snake_case вместо camelCase

2018-10-04 09:39 UTC, leshiy1295 commented on deep_c/1/part1.c
> +typedef char** string_ptr;
можно было бы сделать указатель на массив
тогда проблем с const скорее всего не возникло бы

2018-10-04 09:39 UTC, leshiy1295 commented on deep_c/1/part1.c
> +    string_ptr text;
все переменные нужно явно инициализировать при определении

2018-10-04 09:39 UTC, leshiy1295 commented on deep_c/1/part1.c
> + -1, если не выделилась память */
size_t не может вернуть -1

2018-10-04 09:39 UTC, leshiy1295 commented on deep_c/1/part1.c
> +    wchar_t letter_a_ru = L'а';
Вы передаёте char, в который в таком случае не умещается 2хбайтовый-русский символ (из-за кодировки по умолчанию на UNIX-системах вместо Windows1251 на Windows-системах), а затем сравниваете его часть с полным кодом wchar_t, что тоже некорректно
в задаче не подразумевалась поддержка русского алфавита, поэтому с целью упрощения можно оставить работу только с латинским

2018-10-04 09:39 UTC, leshiy1295 commented on deep_c/1/part1.c
> +void cleanTexts(string_ptr arr, string_ptr text, const size_t size) {
неочевидная сигнатура метода и названия переменных

2018-10-04 09:39 UTC, leshiy1295 commented on deep_c/1/part1.c
> +char correctLetter(char letter) {
это не correctLetter, а какой-нибудь transform_letter или downcase[_letter]

2018-10-05 07:29 UTC, leshiy1295 requested changes

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +/*
main.exe тоже не должно быть в репозитории

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +size_t get_string_length(char arr[]);
get_string... char arr[]
почему не назвать аргумент str или string?

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +size_t downcase_text(char* arr[], const size_t arr_size, string_ptr* save);
то, что arr - то массив строк - ясно из типа
какой-нибудь lines говорил бы о назначении этого параметра больше

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +size_t downcase_text(char* arr[], const size_t arr_size, string_ptr* save);
save - совсем непонятно, что такое

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +size_t get_string(char** lineptr, size_t* n, int delimiter, FILE* stream);
хорошая практика размещать сначала входные параметры, а потом выходные (см. Google C++ StyleGuide)

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +void print_text(string_ptr text, const size_t text_size);
тут опять же интересен не char**, а char *[], причём const, который был бы назван lines, а второй аргумент - lines_count.

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +size_t load_text(string_ptr text);
загрузить? откуда?

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +void free_all_memory(string_ptr first_ptr, string_ptr second_ptr, size_t string_ptr_size);
от того, что параметры имеют тип ptr, а также идут в таком порядке, названия никакой новой информации не дали. Более того - совершенно непонятно, а что такое string_ptr_size тут.
Нужно поменять именования. Возможно, лучше будет, если разбить на несколько методов, если передаваемые сущности совсем никак друг с другом не связаны

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +    string_ptr arr = (string_ptr)calloc(BUFFER_SIZE, sizeof(char*));
память выделяется под string_ptr
а количество памяти оценивается по char *
нужно и там, и там использовать одни обозначения

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +    string_ptr arr = (string_ptr)calloc(BUFFER_SIZE, sizeof(char*));
arr - непонятное название переменной

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +        return ERROR;
где-то возвращается 0, где-то - ERROR
нужно привести к единому интерфейсу
тем более, что ERROR == -1, а size_t хранит беззнаковое целое число

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +    if (text_size == 0) {
если text_size == 0, то создаётся ощущение, что будет утечка arr, поскольку совершенно неожиданно то, что load_text эту память почистит за нас

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +size_t load_text(string_ptr text) {
семантически неверно очищать передаваемую память
представьте, что Вы передали строку в printf, а он взял и память очистил просто вместо того, чтобы выдать ошибку
внутри функции можно очищать только ту память, про которую она знает

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +    } while (get_string(&text[i++], &max_size, '\n', stdin) != ERROR);
если будет ERROR, то i будет уже n + 1, хотя реально прочитанных строк могло быть n
и вообще - не стоит неявно менять таким образом значения

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +    int lines = downcase_text(arr, text_size, &text);
чем lines отличается от text_size?

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +    int lines = downcase_text(arr, text_size, &text);
и что будет, если метод вернёт ERROR?

2018-10-05 07:29 UTC, leshiy1295 commented on deep_c/1/part1.c
> +        printf("[error]");
семантически тоже неверно - мы ожидаем, что будет выведен текст
если произошла ошибка, то нужно вернуть ошибку, дав возможность тому, кто вызвал функцию её обработать самостоятельно

2018-10-07 13:59 UTC, leshiy1295 requested changes

2018-10-07 13:59 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	FILE *f = stdin;
чтобы работать с тестами из файлов, необязательно поддерживать работу с файлами внутри самой программы
можно запускать их так: ./a.out <test.in

2018-10-07 13:59 UTC, leshiy1295 commented on deep_c/1/part1.c
> +#define NO_ERROR 1
вообще обычно - наоборот, если всё ок, то возвращается 0, но пусть так

2018-10-07 13:59 UTC, leshiy1295 commented on deep_c/1/part1.c
> +typedef char (*string_ptr)[STRING_SIZE];
а зачем ограничивать размер?

2018-10-07 13:59 UTC, leshiy1295 commented on deep_c/1/part1.c
> +int get_string(FILE* stream, string_ptr lineptr);
lineptr, но string_ptr

2018-10-07 13:59 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	 if (lines_count == ERROR) {
проблема с отступами

2018-10-07 13:59 UTC, leshiy1295 commented on deep_c/1/part1.c
> +				i = ERROR;
i - это индекс
почему Вы присваиваете флаг ошибки туда же?

2018-10-07 13:59 UTC, leshiy1295 commented on deep_c/1/part1.c
> +		i++;
почему перед тем, как сохранить строку, инкрементируется счётчик?
куда запишется самый первый элемент?

2018-10-07 13:59 UTC, leshiy1295 commented on deep_c/1/part1.c
> +		return --i;
неочевидно, зачем это делается
лучше было переписать на обычный while и инкрементировать по факту успешного добавления, тогда и вычитать бы ничего не пришлось

2018-10-07 13:59 UTC, leshiy1295 commented on deep_c/1/part1.c
> +// ERROR - теперь 0
сбивающий с толку комментарий

2018-10-07 13:59 UTC, leshiy1295 commented on deep_c/1/part1.c
> +    while ((c = fgetc(stream)) != EOF && count != STRING_SIZE - 1) {
а что если длина считываемой строки будет больше STRING_SIZE?
нужно перевыделять буфер
иначе количество считанных таким образом блоков семантически не вяжется в lines_count

2018-10-07 14:19 UTC, SmartPhoneJava commented on deep_c/1/part1.c
> +typedef char (*string_ptr)[STRING_SIZE];
Если не ограничивать размер, то компилятор ругается на индексирование массива с неограниченными границами 
part1.c:151:29: error: invalid use of array with unspecified bounds
             (*downcase_text)[i][j] = downcase_letter(lines[i][j]);

Я конечно понимаю, что можно обращаться к элементам массива через *(downcase_text + i * size_of_row + j), но это как то костыльно...

2018-10-07 15:08 UTC, SmartPhoneJava commented on deep_c/1/part1.c
> +    while ((c = fgetc(stream)) != EOF && count != STRING_SIZE - 1) {
Так ведь мы работаем с string_ptr - указателем на строку размера  - STRING_SIZE, память строки выделяется статически, в перевыделении нет необходимости. 
Если же длина считываемой строки будет больше STRING_SIZE, то она будет хранится в нескольких строках. Например, в пятом тесте строка из пятисот символов Z, она хранится в нашем массиве в виде 16 строк размером 32

2018-10-07 22:10 UTC, SmartPhoneJava commented
Поправил, всё готово к ревью. RunID по прежнему нету, т.к. ejudge все еще не разрешает кидать код...

2018-10-08 12:55 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	load_text(stdin, &input_text, &lines_count);
зачем функция вызывается дважды?
и это не отловилось тестами?

2018-10-08 12:55 UTC, leshiy1295 commented on deep_c/1/part1.c
> +						);
зачем делать такой перенос строки?

2018-10-08 12:55 UTC, leshiy1295 commented on deep_c/1/part1.c
> +	*lines = (string_ptr)calloc(max_lines_count * STRING_SIZE, sizeof(char));
прошлое замечание относилось к тому, что это уже не совсем те строки, поэтому лучше было бы переименовать - например, на blocks_count
по самой логике работы вопросов нет, хоть и изначально планировалось, что вы будете считывать каждую строку в отдельную char *

2018-10-18 11:31 UTC, SmartPhoneJava commented
Теперь и тут с АСТС, runID 1837)

2019-02-11 10:24 UTC, closed without merging