Part2
SmartPhoneJava/technopark pull request #2
Opened 2018-10-03 10:27 UTC by SmartPhoneJava

Второе задание первой лабораторной, runId 670

2018-10-13 16:16 UTC, SmartPhoneJava commented
Алексей, посмотрите пожалуйста, все готово к ревью)

2018-10-15 12:13 UTC, leshiy1295 requested changes

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +/*
exe-файла в репозитории, как и любого другого бинарника, быть не должно

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +#define ERROR_NUMBER_NOT_IN_SET -3
в этом правда есть необходимость?

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +void print_set(const Numeric_set *ns);
обычно в сях подобная задача решается эмуляцией "namespace"-ов - с помощью префиксов методов в виде названия типа структуры
то есть для set:
set_create
set_clear
...

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +void add_from_set_to_set(Numeric_set *to, const Numeric_set *from, int *error);
выходные параметры должны находиться правее входных согласно Google Style Guide, которому мы придерживаемся

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +void unit_tests();
интересное название функции :)

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +    // unit_tests();
а так хорошо всё начиналось :(

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +    char *buffer = NULL, *string = NULL;
не стоит определять больше одной переменной на одной строчке

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +        string = check_string(buffer, &error);
лучше определять переменные как можно ближе к использованию
сейчас string нужна только внутри цикла

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +			free(string);
что-то не так с отступами

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +		// В случае любой ошибочной ситуации get_string не выделяет память, поэтому free
а check_string?

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +        string = check_string(buffer, &error);
check_string по семантике должен возвращать ок/не ок, то есть bool
тут же он возвращает строку..

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +        if (ns->numbers == NULL) {
если realloc вернёт ошибку, то он вернёт NULL, которым Вы перетрёте старое значение указателя, что приведёт к утечке...

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +int push_to_set(Numeric_set *ns, int num) {
push семантически сочетается со стеком и с методом pop
лучше add/remove

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +    from = NULL;
это не имеет никакого смысла, так как from как значение указателя изменится только внутри функции на стеке...

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +Numeric_set *move_set(Numeric_set *from) {
зачем нужна эта функция?

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +typedef struct Numeric_set {
в C согласно naming conventions - названия типов структур должны идти в camelCase со всеми маленькими буквами и с суффиксом _t

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +bool is_symbol_comma(char symbol) {
проще было сделать через именованные константы...
тогда и методов бы не понадобилось...

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +void check_number(const bool after_left_square, bool *after_comma,
совершенно непонятные и запутанные функции
почему они так называются, если они ничего не проверяют?

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +        for (size_t i = 0; i < strsize; i++) {
тут явно код следует разделить на отдельные функции
слишком большой отступ, который не умещается на одном экране

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +        printf(" Failed. Found %d, but need %d", my_error, real_error);
по условию нужно выводить [error] в случае ошибки

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +void printResult(int real_error, int my_error, char *string, char *name) {
sneak_case...

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +    char *stroka = "(";
string/test_string/input_string.. но не stroka...

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +void case_error3() {
называть кейсы тоже нужно адекватно, ибо хороший тестовый фреймворк не гарантирует сохранение порядка их вызова - более того - они обычно выполняются параллельно

2018-10-15 12:13 UTC, leshiy1295 commented on deep_c/1/part2.c
> +    right_tests();
по идеологии тестирования изначально необходимо проверять, что программа работает корректно на правильных данных
и только после этого можно тестировать её на невалидных данных

2018-10-16 05:14 UTC, SmartPhoneJava commented on deep_c/1/part2.c
> +#define ERROR_NUMBER_NOT_IN_SET -3
Отладки ради. Отлавливать 15 разных ошибок одним дефайном было бы проблематично

2018-10-16 05:39 UTC, SmartPhoneJava commented on deep_c/1/part2.c
> +		// В случае любой ошибочной ситуации get_string не выделяет память, поэтому free
check_string не изменяет buffer

2018-10-16 06:13 UTC, SmartPhoneJava commented on deep_c/1/part2.c
> +Numeric_set *move_set(Numeric_set *from) {
Изначально она задумывалась как копирование структуры Numeric_set из старого указателя в новый с обнулением старого, но потом смысл в ней действительно исчез, убираю её.

2018-10-17 09:02 UTC, SmartPhoneJava commented on deep_c/1/part2.c
> +        printf(" Failed. Found %d, but need %d", my_error, real_error);
Но ведь я эти функции написал для отладки, они так и так не пройдут систему тестирования, поскольку здесь собственные входные данные

2018-10-17 09:31 UTC, leshiy1295 commented on deep_c/1/part2.c
> +        printf(" Failed. Found %d, but need %d", my_error, real_error);
если что-то используется только для отладки, то это стоит явно помечать флажком-define, который можно задавать при сборке проекта.
Тогда
#ifdef DEBUG
printf("just for debug");
#endif

2018-10-17 10:33 UTC, SmartPhoneJava commented
Поправил все описанные в комментариях баги\недочеты\отступы\названия_функций и т.д., добавил комментариев для понятности и по возможности пытался называть коммиты так, чтобы было видно, что обновилось. К ревью готов :)

По поводу RunId.... Система автоматического тестирования все еще не хочет пускать меня тестироваться(все то же превышение количества попыток)... но я добавил все тесты в test_all.txt и все проверил, все проходится, ну и мои юнит тесты тоже проходятся :)

2018-10-18 08:20 UTC, leshiy1295 commented
Добрый день!
Лимит Вам подняли - Вы можете снова отправлять своё решение в АСТС

2018-10-18 10:38 UTC, SmartPhoneJava commented
Ура, спасибо!) Залил в АСТС, runID 1829

2018-10-18 12:36 UTC, leshiy1295 requested changes

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +typedef struct numericSet_t {
numeric_set_t

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +int check_string(const char string[]);
bool?

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +void numeric_set_to_char(numericSet_t *ns, char *begin, char *end);
in_string, но to_char

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +bool find_circle_brackets(char string[],
непонятно, где ищутся скобки, и что это за три аргумента

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +         unit_tests();
можно было бы сделать return 0, чтобы не тянуть else...
+ для тестов _DEBUG - не самое очевидное название ENV-переменной

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +					printf("[error]");
обработку ошибки можно провести один раз в самом конце...

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +			if (error == NO_ERROR) {
такой ёлочки можно было бы избежать, если разбить на подфункции и вызывать одну из другой внутри..
сейчас опять main знает обо всём процессе сам

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +		free(buffer);
но ведь buffer будет и так NULL в случае, если всё ок?

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +numericSet_t *set_create(int *error);
set_create выглядит странно, если честно :)

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +	if (ns != NULL) {
а почему тут нет assert, раз такое дело?

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +			return NO_ERROR;
return внутри for использовать недопустимо

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +	size_t iA = 0, iB = 0;
не стоит определять несколько переменных на одной строке

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +	size_t size = 0;
неудачное название
digits_count было бы яснее

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +void work_with_symbol_operator(const bool after_left_square, int *operator_amount,
work_что-то - не самое удачное название метода

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +							int *circle_brackets_amount, int *error) {
беда с выравниванием
как минимум - нужно везде в файле придерживаться одного стиля

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +	*circle_brackets_amount = *circle_brackets_amount - 1;
если circle_brackets_amount == NULL?

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +		} else if (*letter == symbol_space) {
если ничего - можно явно оставить комментарий, что ничего
иначе может создаться впечатление, что этот случай забыли реализовать

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +	*n = 100;
магическая константа...

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +		count++;
предпочитайте использовать ++i вместо i++

2018-10-18 12:36 UTC, leshiy1295 commented on deep_c/1/part2.c
> +	char *string = "[1]()";
лучше явно указать, что это string[], а не указатель на одиночный

2018-10-18 12:39 UTC, SmartPhoneJava commented on deep_c/1/part2.c
> +int check_string(const char string[]);
Но видов ошибок, которые может вернуть check_string() довольно много(чтобы было проще отлаживать)

2018-10-18 13:03 UTC, SmartPhoneJava commented on deep_c/1/part2.c
> +		free(buffer);
Но сам buffer все еще указывает на ту память, а должен указывать в никуда, т.е. в NULL. В get_string память выделится под строку в случае, если 
if (*lineptr == NULL) 
где lineptr - &buffer. 
Если же buffer не приравнять к NULL, то get_string  не выделит память и дальше при записи в буфер пойдет обращение к чужой памяти

2018-10-18 13:18 UTC, SmartPhoneJava commented on deep_c/1/part2.c
> +	if (ns != NULL) {
Возможно я ошибаюсь, но как я понимаю ассерты ставятся для входных данных, которые если придут некорректными, негативно повлияют на работу функции(т.е. функция вернет например код ошибки или если эта ситуация не обрабатывается, то просто будет работать неправильно). В set_clear же можно прислать значение NULL и это ни на что не повлияет.

2018-10-18 15:08 UTC, SmartPhoneJava commented
Исправил. Что нового:
- функции prepare_for_processing() и process(), чтобы разгрузить main
- удалил все work_something(), теперь всё это добро в check_string()
- set_create разбит на несколько функций и не используется указатель с ошибкой, теперь должно выглядеть получше)
- выравнивания, переименований функций и тому подобное
runID 1840

2018-10-19 12:14 UTC, leshiy1295 requested changes

2018-10-19 12:14 UTC, leshiy1295 commented on deep_c/1/part2.c
> +#define ERROR_NUMBER_NOT_IN_SET -3
можно было завести enum с ошибками, чтобы не заводить им явные значения констант...

2018-10-19 12:14 UTC, leshiy1295 commented on deep_c/1/part2.c
> +    size_t iA = 0;
snake_case
лучше полностью написать - index_in_A

2018-10-19 12:14 UTC, leshiy1295 commented on deep_c/1/part2.c
> +    const char symbol_space = ' ';
константы пишутся большими буквами, иначе в коде воспринимаются как обычные переменные

2018-10-19 12:14 UTC, leshiy1295 commented on deep_c/1/part2.c
> +            // Количество скобок уменьшилось
внутренность каждой ветки можно было бы вынести в отдельную функцию
иначе текущая функция очень большая и знает обо всём

2018-10-19 12:14 UTC, leshiy1295 commented on deep_c/1/part2.c
> +    if (circle_brackets_amount > 0) {
этот блок тоже можно вынести в отдельную функцию

2018-10-19 12:14 UTC, leshiy1295 commented on deep_c/1/part2.c
> +            // Если встретили ']', добавляем последнее найденное число
аналогично - можно вынести в отдельную функцию

2018-10-29 10:40 UTC, leshiy1295 reviewed
В целом, код очень добротный (не ручаюсь за качество алгоритма - а за сам код)
не хватает прогона через форматтер какой-нибудь - с отступами всё же есть некоторые недочёты + есть всё же некоторые недочёты, о которых отписался.

2018-10-29 10:40 UTC, leshiy1295 commented on deep_c/1/part2.c
> +    numeric_set_t *ret = set_create(error);
странно, как это компилируется...
set_create не принимает аргументов

2018-10-29 10:40 UTC, leshiy1295 commented on deep_c/1/part2.c
> +            // Количество скобок уменьшилось
так и не поправлено :(

2018-10-29 10:40 UTC, leshiy1295 commented on deep_c/1/part2.c
> +			case '[':
нужно было вынести один раз все операции в константы и везде их переиспользовать

2019-02-11 10:24 UTC, closed without merging